stat_clock_time_ms="5000"
sleep_time_secs="0.01"
watch_dog_timeout_secs="7"
neopixel_ring_pin="GP28"
neopixel_ring_size="60"
neopixel_ring_cursor_size="3"
neopixel_ring_brightness="0.7"
neopixel_stick_pin="GP27"
neopixel_stick_size="20"
neopixel_stick_brightness="0.5"
audio_out_pin="GP21"
hero_switch_pin="GP9"
rotary_encoder_button_pin="GP10"
rotary_encoder_dt_pin="GP11"
rotary_encoder_clock_pin="GP12"