audio_out_pin="GP21"
audio_out_pin="GP21"
hero_switch_pin="GP9"
neopixel_ring_brightness="0.1"
neopixel_ring_cursor_size="5"
neopixel_ring_pin="GP28"
neopixel_ring_size="60"
neopixel_stick_brightness="0.1"
neopixel_stick_pin="GP27"
neopixel_stick_size="20"
rotary_encoder_button_pin="GP10"
rotary_encoder_clock_pin="GP12"
rotary_encoder_dt_pin="GP11"
sleep_time_secs="0.01"
startup_mp3_filename="lib/KJH_PackstartCombo.mp3"
shutdown_mp3_filename="lib/KJH_PackstopDigital.mp3"
firing_mp3_filename="lib/KJH_Nutrona3.mp3"
stat_clock_time_ms="5000"
cyclotron_speed="30"
cyclotron_starting_speed="100"
power_meter_speed="20"
watch_dog_timeout_secs="7"
